package frc.robot.subsystems.drive;

import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;

/** POD Class to hold constants generated by Phoenix Tuner */
public record CommandSwerveDrivetrain(
    SwerveDrivetrainConstants DrivetrainConstants,
    SwerveModuleConstants<?,?,?> FrontLeft,
    SwerveModuleConstants<?,?,?> FrontRight,
    SwerveModuleConstants<?,?,?> RearLeft,
    SwerveModuleConstants<?,?,?> RearRight
) {}
